server.port=8084

aws.region=us-east-1
aws.lambda.endpoint=http://localhost:4566

testcase.service.url=http://localhost:8081/api/testcases/ai
spring.kafka.bootstrap-servers=localhost:9092

gemini.api.key=${GEMINI_API_KEY}

gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
