server.port=8081

spring.data.mongodb.uri=mongodb://localhost:27017/testcase_db

spring.mvc.pathmatch.matching-strategy=ant_path_matcher

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
